packages:
  - gaze 
  - gaze-gui
  - gaze-gnome-extension

repos:
  - gundulabs

postprocess:
  - |
    #!/usr/bin/env bash
    echo "Switch to gaze authentication profile"
    authselect select gaze with-face-simultaneous with-silent-lastlog with-altfiles --force --nobackup
