#!/bin/bash

iface="$1"

for ((i=0; i<20; i++)); do
    if ip -j link show dev "$iface" 2>/dev/null |
       jq -e '
           any(.[0].altnames[]?;
               test("^ns-[0-9]+-[0-9]+-nspawn-"))
       ' >/dev/null
    then
        exec ip link set dev "$iface" master br0 up
    fi

    sleep 0.05
done

exit 0
