# One fully qualified CernVM-FS repository name per line.
cvmfs-config.cern.ch
grid.cern.ch
juno.ihep.ac.cn
dcomputing.ihep.ac.cn
juno_nightlies.ihep.ac.cn
opticks.ihep.ac.cn
sft.cern.ch
software.eessi.io
unpacked.cern.ch
geant4.cern.ch
common.ihep.ac.cn
juno-wg.ihep.ac.cn

