name: Build Ostree Container Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '00 0,8,16 * * *'
  push:
    branches: [ '*' ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fedora:40
      options: --privileged
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build
        env:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
          image: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          composefile: ${{ vars.COMPOSEFILE }} 
        run: |
          dnf -y --enablerepo=updates-testing install rpm-ostree skopeo \
              selinux-policy-targeted /usr/bin/fuse-overlayfs podman
          skopeo login -u $username -p $password $registry
          mkdir -p repo cache
          ostree init --repo=repo --mode=archive
          cp /usr/share/containers/storage.conf /etc/containers/storage.conf
          sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf
          rpm-ostree compose tree --unified-core \
            --repo=repo --cachedir=cache \
            $composefile
          rm -rf cache
          rpm-ostree compose container-encapsulate \
            --repo=repo --cmd /bin/bash --max-layers 64 \
             fedora/41/x86_64/karuboniru-silverblue containers-storage:build_tmp
          podman push --force-compression \
            --retry 8 \
            --compression-format zstd:chunked \
            containers-storage:build_tmp $registry/$image:$tag

        
